import = ["/home/connor/.config/alacritty/alacritty-theme/themes/tokyo-night.toml"]

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Source Code Pro"

[font.italic]
family = "Source Code Pro"

[font.normal]
family = "Source Code Pro"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux"]
program = "/usr/bin/fish"
