[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Noto Sans Mono"

[font.italic]
family = "Noto Sans Mono"

[font.normal]
family = "Noto Sans Mono"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[general]
import = ["/home/connor/.config/alacritty/alacritty-theme/themes/tokyo_night.toml"]
# import = ["/home/connor/.config/alacritty/alacritty-theme/themes/github_light.toml"]

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l", "-c", "/usr/bin/zellij -l compact"]
# args = ["-l", "-c", "tmux"]
