theme = "tokyonight"
# theme = "github_light"

[editor]
scrolloff = 10
line-number = "relative"
auto-save = true
idle-timeout = 0
completion-trigger-len = 3
true-color = true
rulers = [101] # +1 since 0-indexed
color-modes = true
bufferline = "multiple"
text-width = 100
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
left = [
  "mode", "spacer", "version-control", "file-name", "read-only-indicator", 
  "file-modification-indicator"
]
center = ["diagnostics", "spinner", "selections"]
right = ["position", "total-line-numbers", "file-encoding", "mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Would like the ability toggle hidden in case of a lot of hidden files
# git-ignore = false # Want to still see files that are not being tracked

[editor.auto-pairs]
# Only want these only brackets and not string-type words except '"'
# '(' = ')'
'{' = '}'
'[' = ']'
# '"' = '"'

[editor.search]
smart-case = false

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true
# character = "▏"

[editor.soft-wrap]
# enable = true
# wrap-at-text-width = true

####################################################################################################

[keys.insert]
# Rebind for escaping insert mode.
# The "keep_primary_selection" is for getting rid of multiple cursors
# Also saves on exiting insert mode (broken!)
j = { k = ["keep_primary_selection", "normal_mode"] }
k = { j = ["keep_primary_selection", "normal_mode"] }

# Be able to save inside insert mode (broken!)
C-s = ["normal_mode", ":w"]

[keys.select]
# Same as insert mode
j = { k = ["keep_primary_selection", "normal_mode", ":w"] }
k = { j = ["keep_primary_selection", "normal_mode", ":w"] }

[keys.normal]
# Easy save (ideally should save after delay)
C-s = ":w"

# Moving selection up and down lines
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Be able to add cursors in normal mode instead of select mode
n = "extend_search_next"
N = "extend_search_prev"

# Bind previous defaults to ctrl (to be consistent with file picker)
"C-n" = "search_next"
"C-p" = "search_prev"

# When collapsing also remove multiple cursors
";" = ["keep_primary_selection", "collapse_selection"]

# Delete to end of line
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

# Don't keep selection when appending text
a = ["append_mode", "collapse_selection"]
