theme = "tokyonight"

[editor]
line-number = "relative"
scrolloff = 10
rulers = [100]
text-width = 100
true-color = true
auto-save = true
idle-timeout = 500
completion-trigger-len = 4
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Would like the ability toggle hidden in case of a lot of hidden files
git-ignore = false # Want to still see files that are not being tracked
max-depth = 4

[editor.auto-pairs]
# Only want these only brackets and not string-type words except '"'
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]
center = ["mode", "diagnostics", "spinner", "selections", "mode"]
right = ["position", "total-line-numbers", "file-encoding", "mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
# Rebind for escaping insert mode.
# The "keep_primary_selection" is for getting rid of multiple cursors
j = { k = ["keep_primary_selection", "normal_mode"] }
k = { j = ["keep_primary_selection", "normal_mode"] }

[keys.select]
# Same as insert mode
j = { k = ["keep_primary_selection", "normal_mode"] }
k = { j = ["keep_primary_selection", "normal_mode"] }
# Instead of "extend_line_below"
x = "extend_line"

[keys.normal]
# Moving selection up and down lines
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# Change selection to the word under the cursor
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
# Be able to add cursors in normal mode instead of select mode
n = "extend_search_next"
N = "extend_search_prev"
# Bind previous defaults to alt
"A-n" = "search_next"
"A-N" = "search_prev"
# When collapsing also remove multiple cursors
";" = ["keep_primary_selection", "collapse_selection"]
# Delete to end of line
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
# Don't keep selection when appending
a = ["append_mode", "collapse_selection"]
# Same as select mode
x = "extend_line"
