[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

# [language-server.rust-analyzer.server.extraEnv]
# RUSTUP_TOOLCHAIN = "beta"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-", "--quiet"] }

# [[language]]
# name = "c"
# auto-format = true
# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"